version: '3.7'

services:
  mysql:
    container_name: musicas-mysql
    image: musicas-mysql
    build:
      dockerfile: ./dockerfile.mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    networks:
      - musicas-network
    ports:
      - 3306:3306
  app:
    depends_on:
      - mysql
    container_name: musicas-app
    image: musicas-app
    build:
      dockerfile: ./dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8080:8080
    networks:
      - musicas-network

networks:
  musicas-network: